version: '3.3'

services:
  webapp:
    build:
      context: ./
    environment:
      REACT_APP_AUTH_ENDPOINT: https://lamassu.zpd.ikerlan.es:8443/auth
      REACT_APP_AUTH_REALM: "lamassu"
      REACT_APP_AUTH_CLIENT_ID: "frontend"
      REACT_APP_CA_API: "https://lamassu.zpd.ikerlan.es:8087"
      REACT_APP_DMS_API: "https://lamassu.zpd.ikerlan.es:8085"
    ports:
      - 80:80

