version: '3.3'

volumes:
  postgres_data:
      driver: local
      
services:
  postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

  auth:
    image: jboss/keycloak:12.0.4
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      DB_SCHEMA: public
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
        - 8080:8080
    depends_on:
      - postgres
